name: Check Pods
on: [push , workflow_dispatch ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      id: check-pods
      uses: appleboy/ssh-action@v1.0.3
      with:
        proxy_host: ${{ secrets.BASTION_IP }}
        proxy_port: ${{ secrets.BASTION_PORT }}
        proxy_username: ${{ secrets.BASTION_USER }}
        proxy_password: ${{ secrets.BASTION_PASS }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          echo hello
    
    - name: SLack Notification.
      if: steps.check-pods.outputs.crash-pods != 0
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: alarm_k3s
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_COLOR: 'red'
        SLACK_USERNAME: rtCamp
        SLACK_TITLE: "Some pods have crashed"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
